### ISSUE TITLE
Multiple targets revisited

### ISSUE THREAD

**Issue by aldem** [dennypage/dpinger#31]
Hi,

I have read #22 and #24, but I believe that multiple targets support (without decision making) is still makes sense.

The problem is that dpinger creates 4 threads for single host (+ main thread), and I believe that this is a waste of resources and context switches if one has to monitor (say) 100 targets, and even for 10 targets this is a little bit too much, IMHO, especially on embedded systems (async I/O based on libev, for instance, would be more appropriate, but this is another story).

The idea is just to allow multiple targets to be processed by single instance of dpinger, and every report has to be prefixed with target ip/name.

So, the question is - do you have any interest to implement this feature?

**Comment by dennypage** [comment]
I have considered this, but I honestly don’t find the thread argument compelling. 

Dpinger creates a recv thread, a send thread, and a thread to support each type of reporting activity requested. In the default configuration there are 4 threads: main, send, recv, and report.

There really are no excess context switches. The send and recv threads spend 99.9% of their time on the sleep queue. They wake up, execute a system call and a small number of instructions (much less than a quantum), then return to the sleep queue. The only context switch is the system call and sleep queue transition. These are inherent and unavoidable.

Similarly, the report thread spends 99.9% of it’s time on the sleep queue. It wakes up, executes a relatively small number of instructions (again less than a quantum), followed by 1-3 system calls depending upon the IO implementation, and then returns to the sleep queue.  

The main thread spends 100% of its time on the sleep queue until exit.

In short, thread context switching itself is not an issue, regardless of whether it is an embedded system or not. And I would not expect the total number of threads is much of an issue either. I have a few embedded systems lying around, of which my firewall is a good example… It has around 500 threads in normal operation. My NAS runs over 400 threads. And even my barest of bare bone systems, which runs nothing but NTP, has 100 threads.

Dpinger is designed to monitor reliability and latency on communication links. I.E. WAN connections. The need to monitor fifty or more targets is something that I would view as a less than 1% use case. The 95% use case is one or two links. Even with monitoring both IPv4 and IPv6, this gives 4 instances of dpinger, each of which spends almost 100% of its time on the sleep queue. I really don’t see this as a thread resource issue.

In addition to the above, it should be noted that changing dpinger to handle multiple targets per process raises other issues:

- Multiple targets per process requires a hash to index the targets and associate the echo reply with the echo request. This means an increased CPU requirement for each packet sent/received. Alternatively, the association could be encoded in the data payload, but this would increase the minimum send/recv packet size which is even less desirable. 

- The report/socket threads have to include the identity of the targets in the output, requiring the reader to parse this for each and every report. This is undesirable, particularly since the reader has already effectively done this parsing in order to determine which file or socket to open.

- Either all the targets must use the same parameters, intervals, thresholds, and such, or a configuration file must be introduced. And if different intervals are to be supported, then the additional cost and complexity of an event manager is required.

- Restarting the dpinger process to change parameters for a target results in loss and rebuild of state for all targets rather than just the one target. This is seldom desirable.

While some of these tradeoffs might be appropriate for a use case requiring the monitoring of hundreds of targets, for tens of targets they are not appropriate. I don’t want to penalize the 99% in order to optimize for the 1%. This path leads to apinger.

**Comment by dennypage** [comment]
Just for grins, I spun up a hundred dpinger instances on my little NTP system with one second send and reporting intervals. Total CPU utilization for the box was 8%.

**Comment by aldem** [comment]
Denny, thank you for such detailed explanation. You make good arguments, and if you want to keep dpinger simple and for small amount of targets (and low packet rates) - ok, this makes sense.

As to context switches - yes, they are insignificant if you have only few targets and 1 pps rate, but things will surely change if you have tens of targets and at least 10 pps rates - and please do not forget about related interrupts generated in process of handling all those packets.

If you increase reporting interval, the report thread will consume significantly more CPU - and on small devices (like RPi) this is not something that you can ignore.

Just try 10 pps in your test with 100 instances - and check the CPU utilization (especially kernel).

**Comment by dennypage** [comment]
The test I ran was 100 instances with a 1 second probe interval. This is already 100 pps in and out, or 200 pps aggregate. As noted, total CPU, interrupt, system, and user time combined was 8%.

It should be noted that the concept of interrupt handling cost resulting from N pps is actually unrelated to the discussion of multiple target support. Interrupt handling costs are essentially a constant regardless of whether dpinger is running as 1 process or 100.

The 100 target test was only of theoretical value as I don't have 100 WAN links to monitor, nor do I know of anyone who does. And if someone does have 100 links to monitor, I seriously doubt that they would be using a small embedded system to do it.

The frequency of reporting is also unrelated to the discussion of multiple target support. The CPU cost for calculating the average latency and loss is determined by the size of the array it is processing and the frequency with which it is done. This is the same whether dpinger is running as 1 process or 100.

On a general note, why would you Increase the reporting frequency to more than once per second? Many people decrease the reporting frequency to several seconds rather than increasing it. Many also decrease the probe frequency as well. Their comments usually come in the form of "Seriously, how frequently do you need an update on the average latency/loss of a WAN link?"

**Comment by aldem** [comment]
> And if someone does have 100 links to monitor, I seriously doubt that they would be using a small embedded system to do it.

Not everyone could afford powerful system for every situation, sometimes peope have to work with what they already have.

> On a general note, why would you Increase the reporting frequency to more than once per second?

Because with 1pps I do not get any reliable link quality measurement over 10s interval - this is only 10 packets, after all. I have links where where I could detect issues only with 10+ pps.

For simple cases, like "host up/down/significantly disrupted link" 1 pps is (probably) ok, but in my case disruptions are so short and irregular that 1 pps will simply miss them. For regular communications (web, mail etc) this is something that you will never feel, but for near-reatime applications (VoIP, telemetry) this makes a huge difference.

Though, since my use case does not fit even in 1% - please forget about my request, and thank you for your time. I just thought that optimizing and extending dpinger for such "advanced" usage would be more popular.

**Comment by dennypage** [comment]
>> On a general note, why would you Increase the reporting frequency to more than once per second?

> Because with 1pps I do not get any reliable link quality measurement over 10s interval - this is only 10 packets, after all. I have links where where I could detect issues only with 10+ pps.

I think you are conflating reporting interval (-r) with send interval (-s) and time period (-t). See dpinger usage statement and NOTES.md for an explanation. 

Remember that dpinger is reporting average latency and loss over time rather than individual packets. Even if you have short term loss, it will be averaged over the time period when a report is generated.

If you would like help in designing a configuration that will work in your usage case, please contact me via email and I will do my best to help. 

As these issues are unrelated to the single vs. multi process question, I am closing this issue.

**Comment by dennypage** [comment]
FWIW, I ran a test based on my (admittedly minimal) understanding of your use case. 100 instances of dpinger each with the following parameters: -s 100m -t 20s -r 5s. In English, this is each instance conducting 10 probes per second, results averaged over 20 seconds, and status reported every 5 seconds. This gives a loss resolution of approximately .5%. On my NTP system this results in a CPU utilization of around 65%. Upping the report interval to 1s takes it to around 70%.

While CPU wise this should not be a problem even for a Pi, you may run into a problem with IO. 100 instances at 10 pps each is almost a megabit per second of ICMP traffic. That may be asking a bit much from a single Pi. You may want two of them. :)

Please contact me via email if you want to explore more.
